const routes = {
  home: '/',
  authors: '/authors',
  explore: '/featured-assets',
  popularAssets: '/popular-assets',
  about: '/about-us',
  contact: '/contact-us',
  purchases: '/purchases',
  wishlists: '/wishlists',
  reports: '/reports',
  questions: '/questions',
  profile: '/profile',
  sellerAgreement: '/seller-agreement',
  blog: '/blog',
  blogPostUrl: (slug: string) => `/blog/${slug}`,
  categories: '/categories',
  // becomeSeller: '/become-seller',
  checkout: '/checkout',
  help: '/help',
  licensing: '/licensing',
  license: '/license',
  refund: '/refund',
  terms: '/terms',
  privacy: '/privacy',
  cookiePolicy: '/cookie-policy',
  password: '/password',
  feed: '/feed',
  wallet: '/wallet',
  followedShop: '/followed-authors',
  orderUrl: (id: string) => `/orders/${encodeURIComponent(id)}`,
  assetUrl: (slug: string) => `/products/${slug}`,
  games: '/games',
  gameUrl: (slug: string) => `/games/${slug}`,
  myGames: '/my-games',
  tagUrl: (slug: string) => `/products/tags/${slug}`,
  shopUrl: (slug: string) => `/authors/${slug}`,
  asset: (slug: string) => {
    return `/products/${encodeURIComponent(slug)}`
  },
  services: '/services',
  service: (slug: string) => `/services/${slug}`,
  outsourcing: `/services/outsourcing`,
  outsourcingOffer: (path: string) =>
    `/services/outsourcing/${path.replace(/^\/+/, '')}`,
  trainings: '/services/trainings',
  training: (path: string) => `/services/trainings/${path.replace(/^\/+/, '')}`,
  activateProduct: '/activate-product'
}
export default routes
